spring:
  devtools:
   restart:
       exclude: "**/build/**,**/bin/**, **/logs/**"
  config:
    import: optional:file:/etc/config/secrets.yml
  datasource:
    url: jdbc:mysql://localhost:3307/worktrack_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: worktrack
    password: worktrack
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${jwt.secret:bCZ0MWB9STlcNV1MN2xyNClZVm1OV1hTcF8kWS42L1M=}
  expiration: 600000

management:
  metrics:
    tags:
      application: worktrack
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.95,0.99
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


otel:
  instrumentation:
    logback-mdc:
      enabled: true
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
  resource:
    attributes:
      service.name: worktrack

  logs:
    exporter: none
  metrics:
    exporter: none

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

cache.enabled: true
