spring:
  config:
    import:
      - "optional:configserver:"
      - "optional:file:/etc/config/secrets.yml"

  cloud:
    config:
      enabled: true
      import-check:
        enabled: true
      discovery:
        enabled: true
        service-id: config-server
    discovery:
      enabled: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, refresh, prometheus