spring:
  config:
     import: >
       optional:configserver:,
       optional:file:/etc/config/secrets.yml
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh