apiVersion: apps/v1
kind: Deployment
metadata:
  name: worktrack-layered
  namespace: worktrack-layered
  labels:
    app: worktrack-layered
spec:
  replicas: 2  # En az 2 pod olsun, production için önerilir (tek pod riskli)
  selector:
    matchLabels:
      app: worktrack-layered
  template:
    metadata:
      labels:
        app: worktrack-layered
    spec:
      containers:
        - name: worktrack-layered
          image: gcr.io/operating-edge-464110-v6/worktrack-layered:latest
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: int
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: worktrack-layered-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: worktrack-layered-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: worktrack-layered-jwt-secret
                  key: JWT_SECRET
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 4
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000  # Non-root user
            allowPrivilegeEscalation: false
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.4
          command:
            - "/cloud_sql_proxy"
            - "-instances=operating-edge-464110-v6:us-central1:worktrack-layered=tcp:3306"
            - "-credential_file=/secrets/service_account.json"
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets
              readOnly: true
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-sa-secret

---
apiVersion: v1
kind: Service
metadata:
  name: worktrack-layered-service
  namespace: worktrack-layered
  labels:
    app: worktrack-layered
spec:
  selector:
    app: worktrack-layered
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worktrack-layered-hpa
  namespace: worktrack-layered
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worktrack-layered
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60