apiVersion: apps/v1
kind: Deployment
metadata:
  name: worktrack-layered
  namespace: worktrack-layered
  labels:
    app: worktrack-layered
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worktrack-layered
  template:
    metadata:
      labels:
        app: worktrack-layered
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: dockerhub-cred
      containers:
        - name: worktrack-layered
          image: docker.io/${DOCKERHUB_USERNAME}/worktrack-layered:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: int
            - name: OTEL_SDK_DISABLED
              value: "true"
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: worktrack-layered-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: worktrack-layered-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: worktrack-layered-jwt-secret
                  key: JWT_SECRET
          resources:
            requests:
              cpu: "500m"
              memory: "768Mi"
            limits:
              cpu: "1G"
              memory: "1.5Gi"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
            periodSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 4
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh","-c","sleep 5" ]
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.1
          args:
            - "--structured-logs"
            - "--address=0.0.0.0"
            - "--port=3306"
            - "--credentials-file=/secrets/service_account.json"
            - "spartan-impact-470620-a4:europe-central2:worktrack-layered"
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets
              readOnly: true
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          startupProbe:
            tcpSocket:
              port: 3306
            periodSeconds: 2
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-sa-secret
---
apiVersion: v1
kind: Service
metadata:
  name: worktrack-layered-service
  namespace: worktrack-layered
  labels:
    app: worktrack-layered
spec:
  selector:
    app: worktrack-layered
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worktrack-layered-hpa
  namespace: worktrack-layered
  labels:
    app: worktrack-layered
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worktrack-layered
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60