global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: springboot
    metrics_path: /actuator/prometheus  #parse this endpoint
    static_configs:
      - targets: ['host.docker.internal:8000']

rule_files:
  - "alerts/*.yml"