package com.worktrack.dto.response;

public enum ErrorCode {
    AUTHENTICATION_FAILED,
    INVALID_CREDENTIAL,
    DUPLICATE_USER,
    ENTITY_NOT_FOUND,
    VALIDATION_ERROR,
    DB_INTEGRITY,
    DB_DUPLICATE_KEY,
    DB_ACQUIRE_LOCK,
    ACCESS_DENIED,
    DB_QUERY_TIMEOUT,
    FILE_STORAGE_ERROR,
    INTERNAL_ERROR
}
